name: build

trigger:
  tags:
    include: ['v*']
pr: none

pool:
  vmImage: 'ubuntu-20.04'

stages:
  - stage: deploy
    jobs:
      - job: deploy
        displayName: Deploy container
        variables:
          - group: deployment-information
        steps:
          - task: Docker@2
            displayName: Login to docker hub
            inputs:
              command: login
              containerRegistry: dockerhub
          - task: Docker@2
            displayName: Login to github packages
            inputs:
              command: login
              containerRegistry: github-packages-sa
          - script: |
              set -xv  # Echo commands before they are run
              export TAG=${BUILD_SOURCEBRANCH#"refs/tags/v"}
              if [[ "$TAG" == *stable* ]]; then export BUILD_TYPE=stable; else export BUILD_TYPE=latest; fi

              export VERSION=${TAG/stable}
              export BRANCH=`git branch -r --contains ${BUILD_SOURCEBRANCH} | grep -v ${BUILD_SOURCEVERSION} | xargs`
              echo "Building $VERSION On branch $BRANCH"
              if [[ "$VERSION" == *stable* ]] && [[ $BRANCH != "origin/master" ]]; then exit 1; fi
              if [[ "$VERSION" == *dev* ]] && [[ $BRANCH != "origin/dev" ]]; then exit 1; fi

              export VERSION=${VERSION/beta/b}
              export SERIES="`expr $TAG : '\([0-9]\+\.[0-9]\+\.\)'`${BUILD_TYPE}"
              for IMAGE in "cccs/assemblyline-ui-frontend" "docker.pkg.github.com/cybercentrecanada/assemblyline/assemblyline-ui-frontend"
              do
                docker build --build-arg version=$VERSION -t $IMAGE:$TAG -t $IMAGE:$BUILD_TYPE -t $IMAGE:$SERIES .
                docker push $IMAGE --all-tags
              done
            displayName: Deploy to Docker Hub
