name: Deploy Assemblyline Demo to Pages

on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Official Frontend Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Build Official Un-forked Production React App
        run: |
          pnpm install
          pnpm run build  # This outputs the compiled site to the 'build/' folder
        env:
          VITE_BASE: '/assemblyline-ui-frontend/'

      - name: Inject Mock Script for GitHub Pages Demo
        run: |
          sed -i "s|</head>|<script src=\"/assemblyline-ui-frontend/mock-demo.js\"></script></head>|g" build/index.html
          cp build/index.html build/404.html

      - name: Upload Static Assets to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
